---
- hosts: localhost
  vars:
    idrac_user:         "root"
    idrac_password:     ""

  tasks:
  - name: Modify existing iDRAC user username and password
    dellemc.openmanage.idrac_user:
      idrac_ip:       "{{ item.url }}"
      idrac_user:     "{{ idrac_user }}"
      idrac_password: "{{ item.actual_password }}"
      validate_certs: false
      state:          "present"
      user_name:      "{{ idrac_user }}"
      new_user_name:  "{{ idrac_user }}"
      user_password:  "{{ item.new_password }}"
    with_items:
      - {url: "esx29am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx30am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx31am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx32am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx33am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx34am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx35am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx36am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx37am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx38am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx39am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx40am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx41am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx42am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx43am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx44am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx45am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx46am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx47am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx48am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx49am.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx50bm.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx01bm.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx02bm.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx01cm.int.stratio.com", actual_password: "", new_password: ""}
      - {url: "esx02cm.int.stratio.com", actual_password: "", new_password: ""}
