---
- hosts: rc_hp_ilo
  vars:
    hp_bin:           "/usr/bin/hponcfg"
    ilo_user:         "Administrator"
    ilo_password:     ""
    ilo_new_password: ""

  tasks:
  - stat:
      path: {{ hp_bin }}
    register: status_hponcfg

  - debug:
      msg: "hponcfg does not exist"
    when: status_hponcfg.stat.exists == False
    
  - name: Prepare hponcfg configuration XML
    ansible.builtin.copy:
      content: |
          <RIBCL VERSION="2.0">
              <LOGIN USER_LOGIN="{{ ilo_user }}" PASSWORD="{{ ilo_password }}">
                  <USER_INFO MODE="write">
                      <MOD_USER USER_LOGIN="{{ ilo_user }}">
                          <PASSWORD value="{{ ilo_new_password }}"/>
                      </MOD_USER>
                  </USER_INFO>
              </LOGIN>
          </RIBCL>
      dest: /tmp/pwreset.xml

  - name: Configure HP iLO on VMware ESXi hypervisor
    community.general.hponcfg:
      src: /tmp/pwreset.xml
      executable: /opt/tools/hponcfg
