---
# tasks file for monitor-users
- name: CREATE {{monitor_group}} GROUP
  group: name={{monitor_group}} state=present system=yes

- name: CREATE {{monitor_group}} USERS
  user: name={{item.key}} createhome=yes group={{monitor_group}} append=yes shell=/bin/bash state=present
  with_dict: "{{monitor | default({})}}"

- name: CREATE USERS' SSH FOLDER
  file:
   owner={{item}}
   group={{monitor_group}}
   path=/home/{{item}}/.ssh
   state=directory
  with_items: "{{monitor | default([])}}"

- name: INCLUDE USERS' PUBLIC RSA
  copy: content='{{item.value.id_rsa}}' dest='/home/{{item.key}}/.ssh/authorized_keys' owner={{item.key}} group={{monitor_group}} force='yes'
  with_dict: "{{monitor | default({})}}"

- name: ADDING USERS' SUDOERS PERMISIONS
  lineinfile: dest=/etc/sudoers line='{{item.key}} ALL=(ALL:ALL) NOPASSWD:ALL' owner=root group=root mode=0440 validate='visudo -cf %s'
  when: item.value.sudo
  with_dict: "{{monitor | default({})}}"

- name: REMOVING USERS' SUDOERS PERMISIONS
  lineinfile: dest=/etc/sudoers line='{{item.key}} ALL=(ALL:ALL) NOPASSWD:ALL' owner=root group=root mode=0440 state=absent
  when: not item.value.sudo
  with_dict: "{{monitor | default({})}}"

- name: CREATE FORMER USERS LIST
  shell: while IFS=$':' read group n id _members ; do [[ $_members ]] && members+="$_members,"; members+="$(grep -E "^[^:]+:[^:]+:[^:]+:${id}:.*$" /etc/passwd | cut -d ':' -f1 | tr -t '\n' ',')"; echo -n ${members} | tr -t ',' ' ' ; done< <(getent group {{monitor_group}}) | sed -e "s/ $//"
  args:
    executable: /bin/bash
  register: old_monitor_users_temp

- name: REGISTER FORMER USERS LIST
  set_fact: old_monitor_users="{{item}}"
  with_items: "{{old_monitor_users_temp.stdout_lines | list}}"

- name: PURGE ALL OTHER USERS BELONGING TO {{monitor_group}}
  shell: "userdel -r {{item}}"
  with_items: "{{ old_monitor_users.split(\" \") | difference(monitor | default([]) | list) }}"
  when: old_monitor_users is defined

- name: PURGE ALL OTHER USERS BELONGING TO {{monitor_group}} SUDO PERMISIONS
  lineinfile: dest=/etc/sudoers line='{{item}} ALL=(ALL:ALL) NOPASSWD:ALL' owner=root group=root mode=0440 validate='visudo -cf %s' state=absent
  with_items: "{{ old_monitor_users.split(\" \") | difference(monitor | default([]) | list) }}"
  when: old_monitor_users is defined
