---
- hosts:
  become: true
  become_method: enable
  vars:
    new_password:

  tasks:
  - name: Change admin password on switches DellOS 9
    dellos9_config:
      lines:
        - "username admin password 0 {{new_password}} privilege 1"
        - "enable password 0 {{new_password}}"
      match: exact
      save: true
    when:
      - "ansible_network_os == 'dellos9'"

  - name: Change admin password on switches DellOS 6 
    dellos6_config:
      lines:
        - "username \"admin\" password {{new_password}} privilege 15"
        - "enable password {{new_password}}"
      match: exact
      save: true
    when:
      - "ansible_network_os == 'dellos6'"

  - name: Replace old hostname with new hostname (requires Ansible >= 2.4)
    ansible.builtin.replace:
      path: /home/hbermudez/Downloads/litio.ini
      regexp: '{{ item.old }}'
      replace: '{{item.new}}'
    with_items:
      - {old: 'ansible_password=(?!\s*$).+[ ]+ansible_become_method', new: 'ansible_password={{new_password}}       ansible_become_method'}
      - {old: 'ansible_become_password=(?!\s*$).+[ ]+ansible_connection', new: 'ansible_become_password={{new_password}}        ansible_connection'}
    delegate_to: litio
    when:
      - "inventory_hostname == 'litio'"

  - name: Where change password
    debug:
      msg: "Change password on https://llavero.int.stratio.com/app/passwords/view/4c7361e1-f223-4a39-862e-28cbc84f5968 and Rundeck Node password"
