---
- hosts: orgon
  gather_facts: False
  vars:
    env_vlan:   
    env_name:   
    env_range:  

  tasks:
  - name: Create VLAN Interface
    raw: |
      config system interface
        edit Labs_{{ env_vlan }}
          set vdom "root"
          set ip {{ env_range | ipaddr(1) | ipaddr('address') }} {{ env_range | ipaddr(2) | ipaddr('netmask') }}
          set alias Labs_{{ env_name }}
          set device-identification enable
          set role lan
          set interface "port18"
          set vlanid {{ env_vlan }}
        next
      end
    when: "'orgon' in inventory_hostname"

  - name: Create Firewall Address
    raw: |
      config firewall address
        edit Net_Labs_{{ env_name }}_{{ env_range }}
          set color 9
          set allow-routing enable
          set subnet {{ env_range |ipv4('network') }} {{ env_range | ipaddr('netmask') }}
        next
      end
    when: "'orgon' in inventory_hostname"

  - name: Create Firewall Rules
    raw: |
      config firewall policy
        edit 0
          set name "VPN SSL Employees to Labs {{ env_name }}"
          set srcintf "port3"
          set dstintf "Labs_{{ env_vlan }}"
          set srcaddr "Net_VPN-SSL_Employees_10.110.0.0/22"
          set dstaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set action accept
          set schedule "always"
          set service "ALL"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
        edit 0
          set name "Employees to Labs {{ env_name }}"
          set srcintf "port3"
          set dstintf "Labs_{{ env_vlan }}"
          set srcaddr "Net_Employees_172.19.0.0/16" "Net_Employees_Wifi_10.90.0.0/22"
          set dstaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set action accept
          set schedule "always"
          set service "ALL"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
        edit 0
          set name "Labs Rundeck to Labs {{ env_name }}"
          set srcintf "Labs_Gen_500"
          set dstintf "Labs_{{ env_vlan }}"
          set srcaddr "IP_Labs_Rundeck_10.200.0.5"
          set dstaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set action accept
          set schedule "always"
          set service "ALL"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
        edit 0
          set name "Labs Daedalus to Labs {{ env_name }}"
          set srcintf "Labs_Gen_500"
          set dstintf "Labs_{{ env_vlan }}"
          set srcaddr "IP_Labs_Daedalus_10.200.0.66"
          set dstaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set action accept
          set schedule "always"
          set service "ALL"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
        edit 0
          set name "Labs {{ env_name }} to Internet - Colt"
          set srcintf "Labs_{{ env_vlan }}"
          set dstintf "port1"
          set srcaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set dstaddr "all"
          set action accept
          set schedule "always"
          set service "ALL"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
          set nat enable
        next
        edit 0
          set name "Labs {{ env_name }} to Internet - Vodafone"
          set srcintf "Labs_{{ env_vlan }}"
          set dstintf "port2"
          set srcaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set dstaddr "all"
          set action accept
          set schedule "always"
          set service "ALL"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
          set nat enable
        next
        edit 0
          set name "Labs {{ env_name }} to Repo CentOS"
          set srcintf "Labs_{{ env_vlan }}"
          set dstintf "Labs_Gen_500"
          set srcaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set dstaddr "IP_Labs_RepoRedHat_10.200.1.112"
          set action accept
          set schedule "always"
          set service "HTTP"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
        edit 0
          set name "Labs {{ env_name }} to Daedalus"
          set srcintf "Labs_{{ env_vlan }}"
          set dstintf "Labs_Gen_500"
          set srcaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set dstaddr "IP_Labs_Daedalus_10.200.0.66"
          set action accept
          set schedule "always"
          set service "ALL"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
        edit 0
          set name "Labs {{ env_name }} to Nexus"
          set srcintf "Labs_{{ env_vlan }}"
          set dstintf "Pro_CICD_909"
          set srcaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set dstaddr "IP_Production_CICD_Niquel_10.120.14.3"
          set action accept
          set schedule "always"
          set service "DOCKER_REGISTRY" "HTTP" "HTTPS"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
        edit 0
          set name "Labs {{ env_name }} to Molibdeno"
          set srcintf "Labs_{{ env_vlan }}"
          set dstintf "Servers_902"
          set srcaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set dstaddr "IP_Production_Molibdeno_10.120.0.42"
          set action accept
          set schedule "always"
          set service "DNS"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
        edit 0
          set name "Labs {{ env_name }} to Galio"
          set srcintf "Labs_{{ env_vlan }}"
          set dstintf "Servers_902"
          set srcaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set dstaddr "IP_Production_Galio_10.120.0.31"
          set action accept
          set schedule "always"
          set service "NTP"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
        edit 0
          set name "CICD to Labs {{ env_name }}"
          set srcintf "Pro_CICD_909"
          set dstintf "Labs_{{ env_vlan }}"
          set srcaddr "Net_Production_CICD_10.120.14.0/24"
          set dstaddr "Net_Labs_{{ env_name }}_{{ env_range }}"
          set action accept
          set schedule "always"
          set service "ALL"
          set profile-protocol-options "Default Stratio"
          set ssl-ssh-profile "stratio-certificate-inspection"
          set logtraffic all
        next
      end
    when: "'orgon' in inventory_hostname"
