---
# tasks file for stratian-users-htz

- name: CREATE {{stratians_group}} GROUP
  group: 
    name: "{{stratians_group}}" 
    state: present 
    system: yes 
    gid: 38091

- fail:
    msg: You cannot create the users root or operador
  with_dict: "{{stratians | default({})}}"
  when: item.key == 'root'

- name: CREATE {{stratians_group}} USERS
  user: 
    name: "{{item.key}}" 
    createhome: yes
    group: "{{stratians_group}}" 
    append: yes 
    shell: /bin/bash 
    state: present
  with_dict: "{{stratians | default({})}}"
  when: item.key != 'root' 

- name: CREATE USERS' SSH FOLDER
  file:
   owner: "{{item}}"
   group: "{{stratians_group}}"
   path: "/home/{{item}}/.ssh"
   state: directory
  with_items: "{{stratians | default([])}}"
  when: item != 'root'

- name: INCLUDE USERS' PUBLIC RSA
  copy: 
    content: '{{item.value.id_rsa}}' 
    dest: '/home/{{item.key}}/.ssh/authorized_keys' 
    owner: "{{item.key}}" 
    group: "{{stratians_group}}" 
    force: 'yes'
  with_dict: "{{stratians | default({})}}"
  when: item.key != 'root'

- name: ADDING USERS' SUDOERS PERMISIONS
  lineinfile: 
    dest: "/etc/sudoers" 
    line: '{{item.key}} ALL=(ALL:ALL) NOPASSWD:ALL'
    owner: root
    group: root 
    mode: 0440 
    validate: 'visudo -cf %s'
  # when: item.value.sudo
  with_dict: "{{stratians | default({})}}"
  when: item.key != 'root'
