---
# tasks file for stratian-users-htz

- name: CREATE rundeck GROUP
  group: name=rundeck state=present system=yes

- name: CREATE rundeck USERS
  user: name=rundeck createhome=yes group=rundeck append=yes shell=/bin/bash state=present

- name: CREATE USERS' SSH FOLDER
  file:
   owner=rundeck
   group=rundeck
   path=/home/rundeck/.ssh
   state=directory

- name: INCLUDE USERS' PUBLIC RSA
  copy: content='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8At+xQDLH+GpMM97bBjwVBGUEyO4t4o+BvQ/OpQZqtxUbXATvzKH5L3VevF9XRGJdGh6sdHP6eHQov+WsvzLqi4mlfMlki9o0OHGS9iE2XEonPHnjs1S2D4PLNnjye7q+tMH79pcQUo9UHQXJhTQWIH3fAXMHOqFGbh4lBF2wGRwwyQM2GNP/RG0kIdhUp54N1iwxc13/PHxuWNyM75isBRIijEiwmdn2bS6NwWNi5CcmS2wPR0B1QeQfAyaSC5NpIfuBQsO+LqtVh80xXcprH9XspDCWYJuUFU4EVRtJ0BMzbOaYdBceuORaFNbgV8JRjtBNHOgrwGcvFTBioUhcOjAIOvypHLZVWbZJqQ32DQwAaI628RyOSHiwM9Dnks3P0dkZNE8P6eLFtCrqshufun08iHdsM0nCmr6rV3fBFV54/TzRdfQzsn7EAmr39rJC1jl27eezM98E/WUWS2jhMxQpfneyr2TvCoe/bA1NHFzzTGyUkeOYE6wu6T5RnrTpob7znpe1TLH4FMSStKQ+qO0wsONTTdEXZut3+WX0D0hzTKMSu2QZyg26X/NMZ2RgoUuPh/HgyaRVwZRw6XbZ0xLR0W3ZI5jwCsY8OoeWgIIF62nCddX43bUqEDmaI1BV0yEaTgA3wnLDRCmByOirrsbK2f/m/0kmbMHAeGkchw== rundeck' dest='/home/rundeck/.ssh/authorized_keys' owner=rundeck group=rundeck force='yes'

- name: ADDING USERS' SUDOERS PERMISIONS
  lineinfile: dest=/etc/sudoers line='rundeck ALL=(ALL:ALL) NOPASSWD:ALL' owner=root group=root mode=0440 validate='visudo -cf %s'


