---
# tasks file for ntp
- name: Install NTP
  package:
    name: ntp
    state: present

- name: Stop NTP
  systemd:
    state: stopped
    name: ntpd

- name: Update Clock with NTP
  command: ntpd -gq

- name: Start and Enable NTP
  systemd:
    state: started
    name: ntpd
    enabled: yes
