apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keos-pure-pso-ns-ingress-egress
  namespace: keos-pure-pso
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

