---
# defaults file for forti_workstations
forti_agent_deb: "https://links.fortinet.com/forticlient/deb/vpnagent"
forti_agent_deb_location: "/tmp/forticlient.deb"

packages_to_install:
  - libappindicator1
  - libgconf-2-4 
  - libindicator7
  - libnss3-tools