---
- hosts: CICDDEV
  become: true
  become_user: root
  roles:
  - ../roles/keos-portworx
  vars:
    cluster: "cicddev"
    kubernetes_version: "1.24.4"
    portworx_user: "b31c6c67-be40-11eb-a2c5-c24e499c7467"
    portworx_cluster: "cicddevportworx-1b70a72d-ecdf-4322-a6fa-91f24363dc06"
